#! /bin/sh
# prerm for conveyor

# Conveyor runs as a daemon as its own system user. This script stops conveyor
# prior to removing it.

set -e

find /usr/share/skeinforge -name '*.pyc' -exec rm '{}' ';'

#DEBHELPER#

exit 0
